# **Question 1:**

In [ ]:
import numpy as np
arr = np.arange(2, 50, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# **Question 2:**

In [ ]:
l1=[]
l2=[]
print("List 1")

for i in range(0,5):
  k=int(input())
  l1.append(k)
print("List 2")
for i in range(0,5):
  k=int(input())
  l2.append(k)

arr1 = np.array(l1)
arr2 = np.array(l2)
arr = np.concatenate((arr1, arr2))
sorted = np.sort(arr)

print("concated arry: ",arr)
print("sorted array: ",sorted)

List 1
10
20
30
40
50
List 2
1
5
4
3
2
concated arry:  [10 20 30 40 50  1  5  4  3  2]
sorted array:  [ 1  2  3  4  5 10 20 30 40 50]


# **Question 3:**

In [ ]:
arr = np.array([[1,2,3],[1,3,5]])
print("Dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

Dimensions:  2
Size of array:  6


# **Question 4:**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.shape

(10,)

In [ ]:
new_arr=arr[np.newaxis, :]
new_arr.shape

(1, 10)

In [ ]:
arr = np.arange(10)
arr.shape

(10,)

In [ ]:
arr = np.expand_dims(arr, axis=0)
arr.shape

(1, 10)

# **Question 5:**

In [ ]:
arr1 = np.square([1, 2, 3, 4, 5])
arr2 = np.square([6, 7, 8, 9, 10])

print("Horizontal Append :", np.hstack((arr1, arr2)))
print("Vertical Append :", np.vstack((arr1, arr2)))

Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]
Vertical Append : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# **Question 6:**

In [ ]:
arr= np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

unique, counts = np.unique(arr, return_counts=True)
arr = np.asarray((unique, counts))
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 16, 25],
       [ 2,  2,  1,  2,  2,  1,  1,  1,  1,  1,  1,  1]])